### PR TITLE
Fix deadlocking recursive munmap

### LINKED ISSUE #52: Linking a program with gcc hangs
Hi!

I tried compiling a program with gcc on the most recent version of flinux, and figured out that the compilation works fine, but at the very end of the linking step something causes a hang. The output executable is actually produced and working though.
In flog, I see 3 processes while hanging: the first is what I executed from bash, which is waiting for its child. The child executes another process, and waits for that. And the last one, the child of the child, has this log: http://pastebin.com/1e3qV52G 
What's interesting for me is the last 2 lines:

```
[13:27:49.392] (II) DBT block at [102f2000, 10305000) changed. Code cache flushed.
[13:27:49.392] (II) dbt code cache flushed.
```

It seems that after the code cache flushing, nothing happens, but I couldn't figure out more. Does anyone have any idea what's going on?

### PR DESCRIPTION
**Pull request by Sh4rK**
This fixes the recursive munmap deadlock bug by introducing a queue of to-be-munmapped memory regions.
Fixes #52.

This might be totally wrong/stupid, if so, feel free to tell me :)

### CODE REVIEW

**Comment by Sh4rK** [comment]
One problem with this might be that if multiple threads call this at the same time, not all memory might be munmapped. The way that can happen is:
One thread is running the loop in mm_unmap and say, it just processed all elements, but just before calling ReleaseSRWLockExclusive, it gets preempted. Then another thread calls mm_munmap, and adds a new element to the list, but as the lock is acquired, returns normally. Then the first thread releases the lock, but an item is still on the list.
It would of course be munmapped at the next call, so memory wouldn't leak forever. I don't know how big a problem this is.

**Comment by wishstudio** [comment]
You approach looks interesting. Let's think of a way to fix the leakage.
There is also another potential issue I want to note, that there is always a possibility that another thread calls fork() at some point.
In fork() it requires shared lock of mm, which is fine for now since any memory operation requires exclusive lock. But in your modification the `munmap()` routine is now not entirely guarded by the rw lock. If we finally do it this way, we need to make sure that fork() at a middle point of operation won't blow it up.

**Comment by Sh4rK** [comment]
I realized another flaw in this, that if one thread calls munmap, it can stay munmapping for an infinite time if other threads "feed" it blocks though calling munmap. But I have an idea to improve this that is supposed to fix all these problems. Working on it now.

**Comment by Sh4rK** [comment]
I (force-)pushed a better design that I think has none of the flaws discussed above, but please review.
This also removes the heap allocation on the non-recursive path.

**Comment by wishstudio** [comment]
This code is wonderful. It solves all problems I can think of. Even I really don't like the heap functions, I can see it works without any side effects and I cannot think of an alternative yet.

Just a minor issue: I think you should replace `munmap_internal()` with the code between the lock guard in `munmap()`. Your current `munmap_internal()` function is a bit redundant and when called from like `mmap()` or `brk()` it may still deadlock.

**Comment by Sh4rK** [comment]
Can you please describe a case when it could deadlock? I just don't see it myself

**Comment by Sh4rK** [comment]
Ok I think I understand, if munmap_internal causes a recursion into mm_munmap. I'll fix that.

**Comment by wishstudio** [comment]
`munmap_internal()` is always called by functions guarded by mm lock, like `brk()`.
When it calls `munmap_internal()`, it directly calls `munmap_internal_unsafe()`, then if a recursive call occurs from heap, it will call `munmap()`. It has special bits to deal with recursive case, but unfortunately the thread id isn't set in `munmap_internal()` in this case. Then it will deadlock.

**Comment by Sh4rK** [comment]
How about now? (Tip: append `?w=1` to the end of the url on the diff page to ignore whitespace, which makes it much cleaner (I indented a big block of code))

**Comment by wishstudio** [comment]
Merged. Thanks for the work! (and the tip :p)

**Comment by Sh4rK** [comment]
Yay! :D

**Pull request merged**
